using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using flow_weaver_backend.Data.Db;
using flow_weaver_backend.Dtos;
using flow_weaver_backend.Models;
using flow_weaver_backend.Services.Security;
using flow_weaver_backend.Utils.Report;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace flow_weaver_backend.Tests;

// Report artifacts are generated by the agent and by workflow steps, stored
// gzipped in the DB, and downloaded later. Two things here are security-
// relevant and pinned hard: the agent prompt is redacted BEFORE encryption
// (so rotating the cipher offline can never reveal a raw token), and
// LoadContentAsync collapses "forbidden" to null so another user's report ids
// stay unprobeable.
public class ReportServiceTests
{
    private static readonly Guid User = new("22222222-2222-2222-2222-222222222222");

    private sealed class StubExporter : IReportExporter
    {
        public string Format { get; init; } = "html";
        public string ContentType { get; init; } = "text/html";
        public string FileExtension { get; init; } = "html";
        public byte[] Payload { get; set; } = Encoding.UTF8.GetBytes("<html>report</html>");
        public ReportDocument? DocumentSeen { get; private set; }

        public Task<byte[]> ExportAsync(ReportDocument doc, CancellationToken ct)
        {
            DocumentSeen = doc;
            return Task.FromResult(Payload);
        }
    }

    // Replaces anything that looks like a token so the "redact before encrypt"
    // ordering is observable.
    private sealed class StubRedactor : ISecretRedactor
    {
        public (string redacted, bool matched) Redact(string? input)
        {
            if (string.IsNullOrEmpty(input)) return (input ?? string.Empty, false);
            if (!input.Contains("sk-", StringComparison.Ordinal)) return (input, false);
            return (input.Replace("sk-LEAKED", "[REDACTED:apikey]", StringComparison.Ordinal), true);
        }
    }

    private sealed class Fixture : IDisposable
    {
        public AppDbContext Db { get; } = TestDb.NewContext();
        public StubExporter Html { get; } = new();
        public StubExporter Xlsx { get; } = new()
        {
            Format = "xlsx",
            ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            FileExtension = "xlsx",
            Payload = Encoding.UTF8.GetBytes("PK-fake-zip"),
        };

        public ReportService Build(ReportOptions? options = null) => new(
            Db,
            new FakeUser(),
            new IReportExporter[] { Html, Xlsx },
            new FakeCrypto(),
            new StubRedactor(),
            new FakeAudit(),
            new FakeTrace(),
            Options.Create(options ?? new ReportOptions()),
            NullLogger<ReportService>.Instance);

        public void Dispose() => Db.Dispose();
    }

    private static GenerateReportRequest Request(
        string format = "html", string title = "Device Audit", List<ReportSection>? sections = null)
        => new()
        {
            Format = format,
            Document = new ReportDocument
            {
                Title = title,
                Sections = sections ?? new List<ReportSection>(),
            },
        };

    private static ReportGenerationContext Context(
        string? agentPrompt = null, Guid? userId = null)
        => new()
        {
            UserId = userId,
            AgentPrompt = agentPrompt,
        };

    // ─── request validation ─────────────────────────────────────────────

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public async Task MissingFormatIsRejected(string format)
    {
        using var f = new Fixture();

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => f.Build().GenerateAndPersistAsync(Request(format: format), "agent", Context(), default));

        Assert.Contains("format is required", ex.Message);
    }

    // `docx` was here until it became a real format. Replaced rather than deleted:
    // the assertion is that an unknown format is refused, and it needs a name that
    // is genuinely unknown to keep meaning that. `rtf` and `txt` are plausible
    // asks — which is the point, they should be refused clearly rather than
    // rendered as something else.
    [Theory]
    [InlineData("rtf")]
    [InlineData("txt")]
    public async Task UnsupportedFormatIsRejected(string format)
    {
        using var f = new Fixture();

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => f.Build().GenerateAndPersistAsync(Request(format: format), "agent", Context(), default));

        Assert.Contains("unsupported format", ex.Message);
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public async Task MissingTitleIsRejected(string title)
    {
        using var f = new Fixture();

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => f.Build().GenerateAndPersistAsync(Request(title: title), "agent", Context(), default));

        Assert.Contains("title is required", ex.Message);
    }

    // A 100k-row table would blow memory downstream; fail fast with a message
    // that tells the caller what to do.
    [Fact]
    public async Task OversizedTableIsRejectedBeforeExporting()
    {
        using var f = new Fixture();
        var sections = new List<ReportSection>
        {
            new()
            {
                Title = "Devices",
                Tables = new List<ReportTable>
                {
                    new()
                    {
                        Caption = "all devices",
                        Rows = Enumerable.Range(0, 10_001).Select(_ => new List<string> { "x" }).ToList(),
                    },
                },
            },
        };

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => f.Build().GenerateAndPersistAsync(Request(sections: sections), "agent", Context(), default));

        Assert.Contains("cap is 10000", ex.Message);
        Assert.Contains("Paginate", ex.Message);
        Assert.Null(f.Html.DocumentSeen);   // never reached the exporter
    }

    [Fact]
    public async Task ExactlyTenThousandRowsIsAllowed()
    {
        using var f = new Fixture();
        var sections = new List<ReportSection>
        {
            new()
            {
                Title = "Devices",
                Tables = new List<ReportTable>
                {
                    new() { Rows = Enumerable.Range(0, 10_000).Select(_ => new List<string> { "x" }).ToList() },
                },
            },
        };

        var artifact = await f.Build().GenerateAndPersistAsync(
            Request(sections: sections), "agent", Context(), default);

        Assert.NotNull(artifact);
    }

    // A format with no registered exporter is a DI wiring bug — say so.
    [Fact]
    public async Task FormatWithoutARegisteredExporterFailsClearly()
    {
        using var f = new Fixture();

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => f.Build().GenerateAndPersistAsync(Request(format: "pdf"), "agent", Context(), default));

        Assert.Contains("no exporter registered", ex.Message);
        Assert.Contains("DI wiring", ex.Message);
    }

    [Fact]
    public async Task OversizedOutputIsRejected()
    {
        using var f = new Fixture();
        f.Html.Payload = new byte[1024];

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => f.Build(new ReportOptions { MaxBytesPerArtifact = 512 })
                   .GenerateAndPersistAsync(Request(), "agent", Context(), default));

        Assert.Contains("exceeds limit", ex.Message);
        Assert.Empty(f.Db.ReportArtifacts);
    }

    // ─── persistence ────────────────────────────────────────────────────

    [Fact]
    public async Task ArtifactIsPersistedWithExporterMetadata()
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(Request(), "agent", Context(), default);

        Assert.Equal("Device Audit", artifact.Title);
        Assert.Equal("html", artifact.Format);
        Assert.Equal("text/html", artifact.ContentType);
        Assert.Equal("agent", artifact.Source);
        Assert.Equal(f.Html.Payload.Length, artifact.SizeBytes);
        Assert.Single(f.Db.ReportArtifacts);
    }

    // The stamp keeps the header and the stored filename consistent.
    [Fact]
    public async Task GeneratedAtIsStampedWhenTheCallerOmitsIt()
    {
        using var f = new Fixture();

        await f.Build().GenerateAndPersistAsync(Request(), "agent", Context(), default);

        Assert.NotNull(f.Html.DocumentSeen!.GeneratedAt);
    }

    [Fact]
    public async Task CallerSuppliedGeneratedAtIsPreserved()
    {
        using var f = new Fixture();
        var stamp = new DateTime(2020, 1, 2, 3, 4, 5, DateTimeKind.Utc);
        var request = Request();
        request.Document.GeneratedAt = stamp;

        await f.Build().GenerateAndPersistAsync(request, "agent", Context(), default);

        Assert.Equal(stamp, f.Html.DocumentSeen!.GeneratedAt);
    }

    // Workflow handlers have no HTTP user, so they pass one explicitly; if it
    // were ignored the row would land under the wrong owner and be invisible.
    [Fact]
    public async Task ExplicitUserWinsOverTheAmbientOne()
    {
        using var f = new Fixture();
        var otherUser = Guid.NewGuid();

        var artifact = await f.Build().GenerateAndPersistAsync(
            Request(), "workflow", Context(userId: otherUser), default);

        Assert.Equal(otherUser, artifact.UserId);
    }

    [Fact]
    public async Task AmbientUserIsUsedWhenTheContextOmitsIt()
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(Request(), "agent", Context(), default);

        Assert.Equal(User, artifact.UserId);
    }

    [Fact]
    public async Task RetentionExpiryIsStamped()
    {
        using var f = new Fixture();

        var artifact = await f.Build(new ReportOptions { RetentionDays = 30 })
            .GenerateAndPersistAsync(Request(), "agent", Context(), default);

        Assert.True(artifact.ExpiresAt > DateTime.UtcNow.AddDays(29));
        Assert.True(artifact.ExpiresAt < DateTime.UtcNow.AddDays(31));
    }

    // ─── integrity + compression ────────────────────────────────────────

    // The checksum is over the RAW bytes, so it stays comparable whether or not
    // the row happens to be compressed.
    [Fact]
    public async Task Sha256IsComputedOverTheUncompressedBytes()
    {
        using var f = new Fixture();
        var expected = Convert.ToHexString(SHA256.HashData(f.Html.Payload)).ToLowerInvariant();

        var artifact = await f.Build().GenerateAndPersistAsync(Request(), "agent", Context(), default);

        Assert.Equal(expected, artifact.Sha256);
    }

    [Fact]
    public async Task CompressibleFormatsAreGzipped()
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(Request("html"), "agent", Context(), default);

        Assert.True(artifact.IsCompressed);
        Assert.NotEqual(artifact.SizeBytes, artifact.StoredBytes);
        // ...and it really is gzip.
        using var src = new MemoryStream(artifact.ContentBytes);
        using var gz = new GZipStream(src, CompressionMode.Decompress);
        using var dst = new MemoryStream();
        gz.CopyTo(dst);
        Assert.Equal(f.Html.Payload, dst.ToArray());
    }

    // xlsx is already zip-packed; gzipping it only adds header overhead.
    [Fact]
    public async Task AlreadyPackedFormatsAreStoredVerbatim()
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(Request("xlsx"), "agent", Context(), default);

        Assert.False(artifact.IsCompressed);
        Assert.Equal(f.Xlsx.Payload, artifact.ContentBytes);
        Assert.Equal(artifact.SizeBytes, artifact.StoredBytes);
    }

    [Fact]
    public async Task DecompressRoundTripsTheOriginalBytes()
    {
        using var f = new Fixture();
        var svc = f.Build();
        var artifact = await svc.GenerateAndPersistAsync(Request("html"), "agent", Context(), default);

        Assert.Equal(f.Html.Payload, svc.Decompress(artifact));
    }

    [Fact]
    public async Task DecompressPassesUncompressedArtifactsThrough()
    {
        using var f = new Fixture();
        var svc = f.Build();
        var artifact = await svc.GenerateAndPersistAsync(Request("xlsx"), "agent", Context(), default);

        Assert.Equal(f.Xlsx.Payload, svc.Decompress(artifact));
    }

    // ─── prompt redaction (redact BEFORE encrypt) ───────────────────────

    // The stored ciphertext must decrypt to the REDACTED text — otherwise an
    // offline cipher rotation would expose the raw token.
    [Fact]
    public async Task AgentPromptIsRedactedBeforeEncryption()
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(
            Request(), "agent", Context(agentPrompt: "use key sk-LEAKED please"), default);

        Assert.True(artifact.AgentPromptRedacted);
        var decrypted = Encoding.UTF8.GetString(artifact.AgentPromptEncrypted!);
        Assert.Contains("[REDACTED:apikey]", decrypted);
        Assert.DoesNotContain("sk-LEAKED", decrypted);
    }

    // A clean prompt is still encrypted, just not flagged as redacted.
    [Fact]
    public async Task CleanPromptIsStoredEncryptedButNotFlagged()
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(
            Request(), "agent", Context(agentPrompt: "list the edge routers"), default);

        Assert.False(artifact.AgentPromptRedacted);
        Assert.Equal("list the edge routers", Encoding.UTF8.GetString(artifact.AgentPromptEncrypted!));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task AbsentPromptLeavesTheColumnNull(string? prompt)
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(
            Request(), "agent", Context(agentPrompt: prompt), default);

        Assert.Null(artifact.AgentPromptEncrypted);
        Assert.False(artifact.AgentPromptRedacted);
    }

    // ─── filename slugging ──────────────────────────────────────────────

    [Theory]
    [InlineData("Device Audit", "device-audit-")]
    [InlineData("Device_Audit", "device-audit-")]
    [InlineData("Device/Audit!", "deviceaudit-")]
    [InlineData("  Trimmed  ", "trimmed-")]
    public async Task FilenameIsSluggedFromTheTitle(string title, string expectedPrefix)
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(
            Request(title: title), "agent", Context(), default);

        Assert.StartsWith(expectedPrefix, artifact.Filename);
        Assert.EndsWith(".html", artifact.Filename);
    }

    // A title with nothing sluggable still yields a usable filename.
    [Fact]
    public async Task UnsluggableTitleFallsBackToReport()
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(
            Request(title: "!!!"), "agent", Context(), default);

        Assert.StartsWith("report-", artifact.Filename);
    }

    [Fact]
    public async Task LongTitlesAreTruncated()
    {
        using var f = new Fixture();

        var artifact = await f.Build().GenerateAndPersistAsync(
            Request(title: new string('a', 200)), "agent", Context(), default);

        // 60-char slug + "-" + 14-digit stamp + ".html"
        Assert.True(artifact.Filename.Length <= 60 + 1 + 14 + 5, artifact.Filename);
    }

    // ─── LoadContentAsync (the download guard) ──────────────────────────

    private static async Task<Guid> SeedArtifact(
        Fixture f, Guid? userId = null, bool active = true)
    {
        var id = Guid.NewGuid();
        f.Db.ReportArtifacts.Add(new ReportArtifact
        {
            ReportArtifactId = id,
            UserId = userId,
            Title = "t",
            Filename = "t.html",
            ContentType = "text/html",
            Format = "html",
            ContentBytes = Encoding.UTF8.GetBytes("payload"),
            IsCompressed = false,
            Sha256 = "x",
            Source = "agent",
            IsActive = active,
        });
        await f.Db.SaveChangesAsync();
        return id;
    }

    [Fact]
    public async Task LoadContent_OwnerCanRead()
    {
        using var f = new Fixture();
        var id = await SeedArtifact(f, userId: User);

        var bytes = await f.Build().LoadContentAsync(id, User, requesterIsAdmin: false, default);

        Assert.Equal("payload", Encoding.UTF8.GetString(bytes!));
    }

    [Fact]
    public async Task LoadContent_AdminCanReadAnyReport()
    {
        using var f = new Fixture();
        var id = await SeedArtifact(f, userId: Guid.NewGuid());

        var bytes = await f.Build().LoadContentAsync(id, User, requesterIsAdmin: true, default);

        Assert.NotNull(bytes);
    }

    // "Forbidden" collapses to null on purpose: a distinct error would let
    // someone probe which report ids exist.
    [Fact]
    public async Task LoadContent_NonOwnerGetsNullNotAnError()
    {
        using var f = new Fixture();
        var id = await SeedArtifact(f, userId: Guid.NewGuid());

        Assert.Null(await f.Build().LoadContentAsync(id, User, requesterIsAdmin: false, default));
    }

    [Fact]
    public async Task LoadContent_SoftDeletedGetsNull()
    {
        using var f = new Fixture();
        var id = await SeedArtifact(f, userId: User, active: false);

        Assert.Null(await f.Build().LoadContentAsync(id, User, requesterIsAdmin: true, default));
    }

    [Fact]
    public async Task LoadContent_UnknownIdGetsNull()
    {
        using var f = new Fixture();

        Assert.Null(await f.Build().LoadContentAsync(Guid.NewGuid(), User, true, default));
    }

    // An ownerless artifact (workflow-generated) is admin-only.
    [Fact]
    public async Task LoadContent_OwnerlessArtifactIsAdminOnly()
    {
        using var f = new Fixture();
        var id = await SeedArtifact(f, userId: null);

        Assert.Null(await f.Build().LoadContentAsync(id, User, requesterIsAdmin: false, default));
        Assert.NotNull(await f.Build().LoadContentAsync(id, User, requesterIsAdmin: true, default));
    }

    // A compressed row is decompressed on the way out.
    [Fact]
    public async Task LoadContent_DecompressesOnTheWayOut()
    {
        using var f = new Fixture();
        var svc = f.Build();
        var artifact = await svc.GenerateAndPersistAsync(Request("html"), "agent", Context(), default);

        var bytes = await svc.LoadContentAsync(
            artifact.ReportArtifactId, User, requesterIsAdmin: true, default);

        Assert.Equal(f.Html.Payload, bytes);
    }
}
