using System.Text;
using flow_weaver_backend.Dtos;

namespace flow_weaver_backend.Utils.Report.Exporters;

// RFC 4180 CSV with a BOM so Excel on Windows opens it in UTF-8 without
// mangling accents. When a report has more than one table (common for
// audit-style reports) we concatenate them separated by a comment line
// identifying the section — Excel + LibreOffice both display those as
// a plain row, which is the pragmatic tradeoff vs zipping per-table.
public sealed class CsvReportExporter : IReportExporter
{
    public string Format => "csv";
    public string ContentType => "text/csv; charset=utf-8";
    public string FileExtension => "csv";

    public Task<byte[]> ExportAsync(ReportDocument doc, CancellationToken ct)
    {
        var sb = new StringBuilder();

        // Header block — metadata as a two-column table so it reads as
        // regular data instead of broken cells.
        sb.AppendLine(Csv("Report", doc.Title));
        if (!string.IsNullOrWhiteSpace(doc.Subtitle))
            sb.AppendLine(Csv("Subtitle", doc.Subtitle!));
        if (!string.IsNullOrWhiteSpace(doc.GeneratedBy))
            sb.AppendLine(Csv("Generated by", doc.GeneratedBy!));
        sb.AppendLine(Csv("Generated at", (doc.GeneratedAt ?? DateTime.UtcNow).ToString("u")));
        sb.AppendLine();

        // Stats section — flattened as two columns so the CSV stays tabular.
        // Hint/Tone are HTML/PDF styling hints; we omit them from CSV so the
        // file only carries the data the author asked for, not presentation
        // metadata.
        if (doc.Stats.Count > 0)
        {
            sb.AppendLine("# Stats");
            sb.AppendLine(Csv("Label", "Value"));
            foreach (var s in doc.Stats)
                sb.AppendLine(Csv(s.Label, s.Value));
            sb.AppendLine();
        }

        foreach (var section in doc.Sections)
        {
            sb.AppendLine($"# Section: {Sanitize(section.Title)}");
            if (!string.IsNullOrWhiteSpace(section.Description))
                sb.AppendLine($"# {Sanitize(section.Description!)}");

            foreach (var table in section.Tables)
            {
                if (!string.IsNullOrWhiteSpace(table.Caption))
                    sb.AppendLine($"# Table: {Sanitize(table.Caption!)}");
                sb.AppendLine(Csv(table.Headers.ToArray()));
                foreach (var row in table.Rows)
                    sb.AppendLine(Csv(row.ToArray()));
                sb.AppendLine();
            }

            // Same principle as stats: drop the `[tone]` prefix — it's a
            // style badge that belongs in HTML/PDF, not in the CSV payload.
            foreach (var callout in section.Callouts)
                sb.AppendLine(Csv(callout.Title, callout.Body));

            sb.AppendLine();
        }

        // BOM + UTF-8 bytes so Excel picks up the encoding.
        var utf8 = Encoding.UTF8.GetBytes(sb.ToString());
        var bom = new byte[] { 0xEF, 0xBB, 0xBF };
        var result = new byte[bom.Length + utf8.Length];
        Buffer.BlockCopy(bom, 0, result, 0, bom.Length);
        Buffer.BlockCopy(utf8, 0, result, bom.Length, utf8.Length);
        return Task.FromResult(result);
    }

    private static string Csv(params string[] cells)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < cells.Length; i++)
        {
            if (i > 0) sb.Append(',');
            sb.Append(EscapeCell(cells[i] ?? string.Empty));
        }
        return sb.ToString();
    }

    // RFC 4180: if the value contains comma, quote, or newline, wrap in
    // quotes and double any embedded quote.
    private static string EscapeCell(string value)
    {
        var needsQuotes = value.Contains(',') || value.Contains('"')
                          || value.Contains('\n') || value.Contains('\r');
        if (!needsQuotes) return value;
        return "\"" + value.Replace("\"", "\"\"") + "\"";
    }

    // Strip newlines out of comment-style lines so we don't break the CSV
    // at the row level.
    private static string Sanitize(string s) =>
        s.Replace("\r", " ").Replace("\n", " ").Trim();
}
