using ClosedXML.Excel;
using flow_weaver_backend.Dtos;

namespace flow_weaver_backend.Utils.Report.Exporters;

// One workbook with:
//   - "Summary" sheet: doc metadata + stats grid.
//   - One sheet per ReportSection, with each table separated by the
//     callout rows of that section at the bottom.
//
// Tables use bold header + tinted background, frozen top row, and auto
// filter. Severity columns are colored cell-by-cell using ReportTheme.
//
// ClosedXML is heavy-ish but its API lets us keep this single-file and
// readable. We don't stream — the 10 MB cap enforced upstream means the
// whole workbook fits in memory.
public sealed class ExcelReportExporter : IReportExporter
{
    public string Format => "xlsx";
    public string ContentType => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    public string FileExtension => "xlsx";

    public Task<byte[]> ExportAsync(ReportDocument doc, CancellationToken ct)
    {
        using var workbook = new XLWorkbook();

        BuildSummary(workbook, doc);
        foreach (var section in doc.Sections)
            BuildSectionSheet(workbook, section);

        using var ms = new MemoryStream();
        workbook.SaveAs(ms);
        return Task.FromResult(ms.ToArray());
    }

    private static void BuildSummary(XLWorkbook wb, ReportDocument doc)
    {
        var ws = wb.Worksheets.Add("Summary");
        var row = 1;

        ws.Cell(row, 1).Value = "Report";
        ws.Cell(row, 2).Value = doc.Title;
        ws.Cell(row, 1).Style.Font.Bold = true;
        row++;

        if (!string.IsNullOrWhiteSpace(doc.Subtitle))
        {
            ws.Cell(row, 1).Value = "Subtitle";
            ws.Cell(row, 2).Value = doc.Subtitle;
            ws.Cell(row, 1).Style.Font.Bold = true;
            row++;
        }
        if (!string.IsNullOrWhiteSpace(doc.GeneratedBy))
        {
            ws.Cell(row, 1).Value = "Generated by";
            ws.Cell(row, 2).Value = doc.GeneratedBy;
            ws.Cell(row, 1).Style.Font.Bold = true;
            row++;
        }
        ws.Cell(row, 1).Value = "Generated at";
        ws.Cell(row, 2).Value = (doc.GeneratedAt ?? DateTime.UtcNow).ToString("u");
        ws.Cell(row, 1).Style.Font.Bold = true;
        row += 2;

        if (doc.Stats.Count > 0)
        {
            ws.Cell(row, 1).Value = "Stats";
            ws.Cell(row, 1).Style.Font.Bold = true;
            ws.Cell(row, 1).Style.Font.FontSize = 14;
            row++;

            var headerRow = row;
            ws.Cell(row, 1).Value = "Label";
            ws.Cell(row, 2).Value = "Value";
            ws.Cell(row, 3).Value = "Hint";
            ws.Cell(row, 4).Value = "Tone";
            StyleHeaderRow(ws, row, 4);
            row++;

            foreach (var s in doc.Stats)
            {
                ws.Cell(row, 1).Value = s.Label;
                ws.Cell(row, 2).Value = s.Value;
                ws.Cell(row, 3).Value = s.Hint ?? string.Empty;
                ws.Cell(row, 4).Value = s.Tone;
                ApplyToneToCell(ws.Cell(row, 4), s.Tone);
                row++;
            }

            ws.Range(headerRow, 1, row - 1, 4).SetAutoFilter();
            ws.SheetView.FreezeRows(headerRow);
        }

        ws.Columns().AdjustToContents();
    }

    private static void BuildSectionSheet(XLWorkbook wb, ReportSection section)
    {
        var ws = wb.Worksheets.Add(SanitizeSheetName(section.Title));
        var row = 1;

        ws.Cell(row, 1).Value = section.Title;
        ws.Cell(row, 1).Style.Font.Bold = true;
        ws.Cell(row, 1).Style.Font.FontSize = 14;
        row++;
        if (!string.IsNullOrWhiteSpace(section.Description))
        {
            ws.Cell(row, 1).Value = section.Description;
            ws.Cell(row, 1).Style.Font.Italic = true;
            row++;
        }
        row++;

        foreach (var table in section.Tables)
        {
            if (!string.IsNullOrWhiteSpace(table.Caption))
            {
                ws.Cell(row, 1).Value = table.Caption;
                ws.Cell(row, 1).Style.Font.Bold = true;
                row++;
            }
            var headerRow = row;
            for (var c = 0; c < table.Headers.Count; c++)
                ws.Cell(headerRow, c + 1).Value = table.Headers[c];
            if (table.Headers.Count > 0)
                StyleHeaderRow(ws, headerRow, table.Headers.Count);
            row++;

            foreach (var dataRow in table.Rows)
            {
                for (var c = 0; c < dataRow.Count; c++)
                {
                    var cell = ws.Cell(row, c + 1);
                    cell.Value = dataRow[c];
                    if (table.SeverityColumns is not null
                        && table.SeverityColumns.TryGetValue(c, out var sev))
                    {
                        ApplyToneToCell(cell, sev);
                    }
                }
                row++;
            }

            if (table.Headers.Count > 0 && table.Rows.Count > 0)
                ws.Range(headerRow, 1, row - 1, table.Headers.Count).SetAutoFilter();

            row++;
        }

        foreach (var callout in section.Callouts)
        {
            ws.Cell(row, 1).Value = $"[{callout.Tone}] {callout.Title}";
            ws.Cell(row, 2).Value = callout.Body;
            ApplyToneToCell(ws.Cell(row, 1), callout.Tone);
            row++;
        }

        if (ws.FirstRowUsed() is not null)
            ws.SheetView.FreezeRows(1);
        ws.Columns().AdjustToContents();
    }

    private static void StyleHeaderRow(IXLWorksheet ws, int row, int lastColumn)
    {
        var range = ws.Range(row, 1, row, lastColumn);
        range.Style.Font.Bold = true;
        range.Style.Fill.BackgroundColor = XLColor.FromHtml(ReportTheme.AccentLight);
        range.Style.Font.FontColor = XLColor.FromHtml(ReportTheme.AccentDark);
        range.Style.Border.BottomBorder = XLBorderStyleValues.Medium;
        range.Style.Border.BottomBorderColor = XLColor.FromHtml(ReportTheme.BorderFocus);
    }

    private static void ApplyToneToCell(IXLCell cell, string? tone)
    {
        cell.Style.Fill.BackgroundColor = XLColor.FromHtml(ReportTheme.ToneBackground(tone));
        cell.Style.Font.FontColor = XLColor.FromHtml(ReportTheme.ToneColor(tone));
        cell.Style.Font.Bold = true;
    }

    // Excel sheet names: max 31 chars, no :\/?*[].
    private static string SanitizeSheetName(string title)
    {
        var invalid = new[] { ':', '\\', '/', '?', '*', '[', ']' };
        var cleaned = new string((title ?? "Section")
            .Where(c => !invalid.Contains(c)).ToArray())
            .Trim();
        if (cleaned.Length == 0) cleaned = "Section";
        return cleaned.Length > 31 ? cleaned.Substring(0, 31) : cleaned;
    }
}
