using flow_weaver_backend.Dtos;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace flow_weaver_backend.Utils.Report.Exporters;

// A4 PDF mirroring the look of reporte.html — gradient-title hero,
// tinted stat cards, section headers with category color, tables with
// bold header + zebra rows + severity badges, bordered callouts. We
// don't embed custom fonts; QuestPDF falls back to its bundled Inter
// alternative which renders close enough to the web version.
//
// QuestPDF community license is set globally in Program.cs once; calling
// it per-export is both redundant and a surprise gotcha during tests.
public sealed class PdfReportExporter : IReportExporter
{
    public string Format => "pdf";
    public string ContentType => "application/pdf";
    public string FileExtension => "pdf";

    public Task<byte[]> ExportAsync(ReportDocument doc, CancellationToken ct)
    {
        var bytes = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(36);
                page.DefaultTextStyle(t => t.FontFamily("Helvetica").FontSize(10).FontColor(ReportTheme.Text));

                page.Header().Element(h => ComposeHeader(h, doc));
                page.Content().Column(col =>
                {
                    col.Spacing(14);
                    if (doc.Stats.Count > 0) col.Item().Element(s => ComposeStats(s, doc.Stats));
                    foreach (var section in doc.Sections)
                        col.Item().Element(e => ComposeSection(e, section));
                });
                page.Footer().AlignCenter().Text(t =>
                {
                    t.DefaultTextStyle(s => s.FontSize(8).FontColor(ReportTheme.TextMuted));
                    t.Span("Generated by FlowWeaver · page ");
                    t.CurrentPageNumber();
                    t.Span(" of ");
                    t.TotalPages();
                });
            });
        }).GeneratePdf();

        return Task.FromResult(bytes);
    }

    private static void ComposeHeader(IContainer container, ReportDocument doc)
    {
        container.PaddingBottom(12).Column(col =>
        {
            col.Spacing(4);
            if (!string.IsNullOrWhiteSpace(doc.Badge))
            {
                col.Item().Background(ReportTheme.AccentLight)
                    .Padding(4).Border(1).BorderColor(ReportTheme.BorderFocus)
                    .AlignCenter().Text(doc.Badge!)
                    .FontSize(8).FontColor(ReportTheme.Accent).Bold();
            }
            col.Item().Text(doc.Title)
                .FontSize(20).Bold().FontColor(ReportTheme.AccentDark);
            if (!string.IsNullOrWhiteSpace(doc.Subtitle))
                col.Item().Text(doc.Subtitle!).FontSize(10).FontColor(ReportTheme.TextMuted);

            var gen = doc.GeneratedAt ?? DateTime.UtcNow;
            var metaText = $"Generated {gen:yyyy-MM-dd HH:mm 'UTC'}"
                         + (string.IsNullOrWhiteSpace(doc.GeneratedBy) ? "" : $" · {doc.GeneratedBy}");
            col.Item().Text(metaText).FontSize(8).FontColor(ReportTheme.TextMuted);
        });
    }

    private static void ComposeStats(IContainer container, IReadOnlyList<ReportStat> stats)
    {
        // Grid of up to 4 columns; wrap as needed by splitting into rows.
        const int perRow = 4;
        container.Column(col =>
        {
            for (var i = 0; i < stats.Count; i += perRow)
            {
                var slice = stats.Skip(i).Take(perRow).ToList();
                col.Item().Row(row =>
                {
                    row.Spacing(8);
                    foreach (var stat in slice)
                    {
                        row.RelativeItem().Background(ReportTheme.Surface)
                            .Border(1).BorderColor(ReportTheme.Border)
                            .Padding(10)
                            .Column(c =>
                            {
                                c.Item().Text(stat.Label.ToUpperInvariant())
                                    .FontSize(7).FontColor(ReportTheme.TextMuted).Bold();
                                c.Item().PaddingTop(4).Text(stat.Value)
                                    .FontSize(18).Bold().FontColor(ReportTheme.ToneColor(stat.Tone));
                                if (!string.IsNullOrWhiteSpace(stat.Hint))
                                    c.Item().PaddingTop(2).Text(stat.Hint!)
                                        .FontSize(7).FontColor(ReportTheme.TextMuted);
                            });
                    }
                    // Pad empty slots to keep stats aligned when the last row is short.
                    for (var pad = slice.Count; pad < perRow; pad++)
                        row.RelativeItem();
                });
            }
        });
    }

    private static void ComposeSection(IContainer container, ReportSection section)
    {
        var (catFg, catBg, catBorder) = ReportTheme.Category(section.Category);

        container.Column(col =>
        {
            col.Spacing(6);
            col.Item().Text(section.Title).FontSize(14).Bold().FontColor(ReportTheme.Text);
            if (!string.IsNullOrWhiteSpace(section.Description))
                col.Item().Text(section.Description!).FontSize(9).FontColor(ReportTheme.TextMuted);

            foreach (var table in section.Tables)
            {
                if (!string.IsNullOrWhiteSpace(table.Caption))
                {
                    col.Item().Background(catBg).Border(1).BorderColor(catBorder)
                        .Padding(6).Text(table.Caption!)
                        .FontSize(10).Bold().FontColor(catFg);
                }
                col.Item().Element(e => ComposeTable(e, table));
            }

            foreach (var callout in section.Callouts)
                col.Item().Element(e => ComposeCallout(e, callout));
        });
    }

    private static void ComposeTable(IContainer container, ReportTable table)
    {
        container.Table(t =>
        {
            t.ColumnsDefinition(cd =>
            {
                for (var i = 0; i < Math.Max(1, table.Headers.Count); i++)
                    cd.RelativeColumn();
            });

            // Header
            t.Header(h =>
            {
                for (var i = 0; i < table.Headers.Count; i++)
                {
                    h.Cell().Background(ReportTheme.SurfaceAlt)
                        .Border(0.5f).BorderColor(ReportTheme.Border)
                        .Padding(6).Text(table.Headers[i])
                        .FontSize(8).Bold().FontColor(ReportTheme.TextMuted);
                }
            });

            // Rows with zebra + severity highlighting
            for (var r = 0; r < table.Rows.Count; r++)
            {
                var row = table.Rows[r];
                var zebra = r % 2 == 1 ? ReportTheme.SurfaceAlt : ReportTheme.Surface;
                for (var c = 0; c < row.Count; c++)
                {
                    var value = row[c];
                    var cell = t.Cell().Border(0.5f).BorderColor(ReportTheme.Border);

                    if (table.SeverityColumns is not null
                        && table.SeverityColumns.TryGetValue(c, out var sev))
                    {
                        cell.Background(ReportTheme.ToneBackground(sev))
                            .Padding(6).Text(value)
                            .FontSize(8).FontColor(ReportTheme.ToneColor(sev)).Bold();
                    }
                    else
                    {
                        cell.Background(zebra).Padding(6).Text(value)
                            .FontSize(8).FontColor(ReportTheme.Text);
                    }
                }
            }
        });
    }

    private static void ComposeCallout(IContainer container, ReportCallout callout)
    {
        var bar = ReportTheme.ToneColor(callout.Tone);
        var bg = ReportTheme.ToneBackground(callout.Tone);

        container.Row(row =>
        {
            row.ConstantItem(4).Background(bar);
            row.RelativeItem().Background(bg).Padding(10).Column(c =>
            {
                c.Item().Text(callout.Title).FontSize(10).Bold().FontColor(ReportTheme.Text);
                c.Item().PaddingTop(2).Text(callout.Body).FontSize(9).FontColor(ReportTheme.Text);
            });
        });
    }
}
