using flow_weaver_backend.Data.Db;
using Microsoft.EntityFrameworkCore;
using VendorCommandModel = flow_weaver_backend.Models.VendorCommand;

namespace flow_weaver_backend.Services.Ai.Seed;

// Seeds the vendor_commands catalog with a curated baseline covering
// the ssh.md device_type matrix (cisco_ios, cisco_xe, cisco_xr,
// cisco_nxos, juniper_junos, arista_eos, nokia_sros, nokia_srl, huawei,
// fortinet, linux). The baseline lands at first boot; admins extend it
// via the /vendor-commands UI.
//
// Idempotent by (DeviceType, Kind, Value): existing rows are
// left alone, missing rows are inserted. Rows the admin deleted (Source
// stays "seed" but IsActive=false) are NOT re-added — that would defeat
// the point of letting admins curate the catalog.
//
// User-authored rows (Source="user") are always preserved; the seed
// only ever inserts new rows, never updates or removes.
public static class DefaultVendorCommandsSeedService
{
    private sealed record CatalogEntry(string Kind, string Value);

    private sealed record VendorCatalog(
        string DeviceType,
        string VendorFamily,
        IReadOnlyList<CatalogEntry> Entries);

    // Pattern shorthand for "any `show <something>` form" — covers most
    // read-only verbs without enumerating every subcommand. Vendor-
    // specific variants (config terminal, request system reboot, …) are
    // listed as `exact` entries so the admin can revoke a single one.
    private const string ShowAnythingCisco = @"^show\s+\S+(\s+\S+)*$";
    private const string ShowAnythingArista = @"^show\s+\S+(\s+\S+)*$";
    private const string ShowAnythingHuawei = @"^display\s+\S+(\s+\S+)*$";
    private const string JunosShow = @"^show\s+\S+(\s+\S+)*$";
    private const string SrosShow = @"^show\s+\S+(\s+\S+)*$";
    private const string FortinetGet = @"^get\s+\S+(\s+\S+)*$";
    private const string LinuxStat = @"^(ls|cat|tail|head|grep|ps|ip|uname|hostname|uptime|df|free|systemctl\s+status\s+\S+)(\s+\S+)*$";

    private static readonly VendorCatalog[] Catalogs =
    {
        // Cisco IOS / classic IOS (Catalyst, ISR, etc.). Patterns cover
        // all `show ...` and most `terminal ...` forms; exact entries
        // give the agent a curated suggestion set for typos.
        new("cisco_ios", "cisco", new[]
        {
            // System / version
            new CatalogEntry("exact", "show version"),
            new CatalogEntry("exact", "show running-config"),
            new CatalogEntry("exact", "show startup-config"),
            new CatalogEntry("exact", "show inventory"),
            new CatalogEntry("exact", "show platform"),
            new CatalogEntry("exact", "show hardware"),
            new CatalogEntry("exact", "show flash"),
            new CatalogEntry("exact", "show file systems"),
            new CatalogEntry("exact", "show boot"),
            new CatalogEntry("exact", "show tech-support"),
            new CatalogEntry("exact", "show clock"),
            new CatalogEntry("exact", "show ntp status"),
            new CatalogEntry("exact", "show ntp associations"),
            new CatalogEntry("exact", "show users"),
            new CatalogEntry("exact", "show sessions"),
            new CatalogEntry("exact", "show line"),
            new CatalogEntry("exact", "show logging"),
            new CatalogEntry("exact", "show processes cpu"),
            new CatalogEntry("exact", "show processes cpu sorted"),
            new CatalogEntry("exact", "show processes memory"),
            new CatalogEntry("exact", "show memory"),
            new CatalogEntry("exact", "show environment"),
            new CatalogEntry("exact", "show power"),
            new CatalogEntry("exact", "show diag"),
            // Interfaces
            new CatalogEntry("exact", "show interfaces"),
            new CatalogEntry("exact", "show interfaces description"),
            new CatalogEntry("exact", "show interfaces status"),
            new CatalogEntry("exact", "show interfaces summary"),
            new CatalogEntry("exact", "show interfaces counters"),
            new CatalogEntry("exact", "show interfaces counters errors"),
            new CatalogEntry("exact", "show interfaces transceiver"),
            new CatalogEntry("exact", "show interfaces transceiver detail"),
            new CatalogEntry("exact", "show ip interface brief"),
            new CatalogEntry("exact", "show ip interface"),
            new CatalogEntry("exact", "show ipv6 interface brief"),
            // Switching
            new CatalogEntry("exact", "show vlan"),
            new CatalogEntry("exact", "show vlan brief"),
            new CatalogEntry("exact", "show mac address-table"),
            new CatalogEntry("exact", "show mac address-table dynamic"),
            new CatalogEntry("exact", "show spanning-tree"),
            new CatalogEntry("exact", "show spanning-tree summary"),
            new CatalogEntry("exact", "show etherchannel summary"),
            new CatalogEntry("exact", "show etherchannel detail"),
            new CatalogEntry("exact", "show port-security"),
            new CatalogEntry("exact", "show errdisable"),
            new CatalogEntry("exact", "show errdisable recovery"),
            // Discovery
            new CatalogEntry("exact", "show cdp neighbors"),
            new CatalogEntry("exact", "show cdp neighbors detail"),
            new CatalogEntry("exact", "show lldp neighbors"),
            new CatalogEntry("exact", "show lldp neighbors detail"),
            new CatalogEntry("exact", "show lldp interface"),
            // Routing — base
            new CatalogEntry("exact", "show ip route"),
            new CatalogEntry("exact", "show ip route summary"),
            new CatalogEntry("exact", "show ipv6 route"),
            new CatalogEntry("exact", "show ip protocols"),
            new CatalogEntry("exact", "show ip arp"),
            new CatalogEntry("exact", "show arp"),
            new CatalogEntry("exact", "show ipv6 neighbors"),
            new CatalogEntry("exact", "show ip cef"),
            new CatalogEntry("exact", "show vrf"),
            new CatalogEntry("exact", "show vrf brief"),
            new CatalogEntry("exact", "show ip vrf"),
            new CatalogEntry("exact", "show ip vrf interfaces"),
            // OSPF / EIGRP / BGP
            new CatalogEntry("exact", "show ip ospf"),
            new CatalogEntry("exact", "show ip ospf neighbor"),
            new CatalogEntry("exact", "show ip ospf interface"),
            new CatalogEntry("exact", "show ip ospf database"),
            new CatalogEntry("exact", "show ip eigrp neighbors"),
            new CatalogEntry("exact", "show ip eigrp topology"),
            new CatalogEntry("exact", "show ip eigrp interfaces"),
            new CatalogEntry("exact", "show ip bgp summary"),
            new CatalogEntry("exact", "show bgp summary"),
            new CatalogEntry("exact", "show ip bgp neighbors"),
            new CatalogEntry("exact", "show ip bgp"),
            // Redundancy
            new CatalogEntry("exact", "show standby"),
            new CatalogEntry("exact", "show standby brief"),
            new CatalogEntry("exact", "show vrrp"),
            new CatalogEntry("exact", "show vrrp brief"),
            new CatalogEntry("exact", "show hsrp"),
            // ACLs
            new CatalogEntry("exact", "show access-lists"),
            new CatalogEntry("exact", "show ip access-lists"),
            // Terminal / mode
            new CatalogEntry("exact", "terminal length 0"),
            new CatalogEntry("exact", "terminal monitor"),
            new CatalogEntry("exact", "terminal no monitor"),
            new CatalogEntry("exact", "enable"),
            new CatalogEntry("exact", "disable"),
            new CatalogEntry("exact", "configure terminal"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "end"),
            // Connectivity / utility
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "traceroute"),
            new CatalogEntry("exact", "telnet"),
            new CatalogEntry("exact", "ssh"),
            new CatalogEntry("exact", "write memory"),
            new CatalogEntry("exact", "copy running-config startup-config"),
            // Patterns — broad coverage
            new CatalogEntry("pattern", ShowAnythingCisco),
            new CatalogEntry("pattern", @"^show\s+running-config(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+ip\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+ipv6\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+interfaces?\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^terminal\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^configure(\s+terminal)?$"),
            new CatalogEntry("pattern", @"^copy\s+\S+\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^ping(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute(\s+\S+)+$"),
        }),
        // Cisco IOS-XE (Catalyst 9k, ISR4k, ASR1k). Almost identical to
        // classic IOS at the user-facing CLI but adds platform/install
        // commands. Pattern coverage delegates to the classic-IOS
        // patterns; exact entries highlight XE-only commands.
        new("cisco_xe", "cisco", new[]
        {
            new CatalogEntry("exact", "show version"),
            new CatalogEntry("exact", "show running-config"),
            new CatalogEntry("exact", "show startup-config"),
            new CatalogEntry("exact", "show ip interface brief"),
            new CatalogEntry("exact", "show ipv6 interface brief"),
            new CatalogEntry("exact", "show interfaces"),
            new CatalogEntry("exact", "show interfaces description"),
            new CatalogEntry("exact", "show interfaces status"),
            new CatalogEntry("exact", "show interfaces transceiver"),
            new CatalogEntry("exact", "show ip route"),
            new CatalogEntry("exact", "show ipv6 route"),
            new CatalogEntry("exact", "show ip route summary"),
            new CatalogEntry("exact", "show ip arp"),
            new CatalogEntry("exact", "show platform"),
            new CatalogEntry("exact", "show platform software"),
            new CatalogEntry("exact", "show platform hardware"),
            new CatalogEntry("exact", "show inventory"),
            new CatalogEntry("exact", "show install summary"),
            new CatalogEntry("exact", "show install active"),
            new CatalogEntry("exact", "show install committed"),
            new CatalogEntry("exact", "show environment"),
            new CatalogEntry("exact", "show environment all"),
            new CatalogEntry("exact", "show power"),
            new CatalogEntry("exact", "show clock"),
            new CatalogEntry("exact", "show users"),
            new CatalogEntry("exact", "show logging"),
            new CatalogEntry("exact", "show processes cpu"),
            new CatalogEntry("exact", "show processes memory"),
            new CatalogEntry("exact", "show vlan brief"),
            new CatalogEntry("exact", "show vlan"),
            new CatalogEntry("exact", "show mac address-table"),
            new CatalogEntry("exact", "show spanning-tree"),
            new CatalogEntry("exact", "show cdp neighbors"),
            new CatalogEntry("exact", "show cdp neighbors detail"),
            new CatalogEntry("exact", "show lldp neighbors"),
            new CatalogEntry("exact", "show lldp neighbors detail"),
            new CatalogEntry("exact", "show ip bgp summary"),
            new CatalogEntry("exact", "show ip ospf neighbor"),
            new CatalogEntry("exact", "show ip protocols"),
            new CatalogEntry("exact", "show vrf"),
            new CatalogEntry("exact", "show vrf brief"),
            new CatalogEntry("exact", "show etherchannel summary"),
            new CatalogEntry("exact", "show standby brief"),
            new CatalogEntry("exact", "show ip access-lists"),
            new CatalogEntry("exact", "show tech-support"),
            new CatalogEntry("exact", "terminal length 0"),
            new CatalogEntry("exact", "enable"),
            new CatalogEntry("exact", "configure terminal"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "end"),
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "traceroute"),
            new CatalogEntry("exact", "write memory"),
            new CatalogEntry("exact", "copy running-config startup-config"),
            new CatalogEntry("pattern", ShowAnythingCisco),
            new CatalogEntry("pattern", @"^show\s+running-config(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+ip\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+ipv6\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+platform\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^terminal\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^configure(\s+terminal)?$"),
            new CatalogEntry("pattern", @"^copy\s+\S+\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^ping(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute(\s+\S+)+$"),
        }),
        // Cisco IOS-XR (ASR9k, NCS, CRS). Distinct CLI: `show route`
        // (not `show ip route`), `commit` model, separate admin plane.
        new("cisco_xr", "cisco", new[]
        {
            // System
            new CatalogEntry("exact", "show version"),
            new CatalogEntry("exact", "show running-config"),
            new CatalogEntry("exact", "show inventory"),
            new CatalogEntry("exact", "show platform"),
            new CatalogEntry("exact", "show install active"),
            new CatalogEntry("exact", "show install committed"),
            new CatalogEntry("exact", "show install summary"),
            new CatalogEntry("exact", "show environment"),
            new CatalogEntry("exact", "show environment power"),
            new CatalogEntry("exact", "show environment temperature"),
            new CatalogEntry("exact", "show controllers"),
            new CatalogEntry("exact", "show hw-module fpd"),
            new CatalogEntry("exact", "show hw-module fpd location all"),
            new CatalogEntry("exact", "show clock"),
            new CatalogEntry("exact", "show users"),
            new CatalogEntry("exact", "show logging"),
            new CatalogEntry("exact", "show processes cpu"),
            new CatalogEntry("exact", "show processes memory"),
            new CatalogEntry("exact", "show tech-support"),
            // Interfaces
            new CatalogEntry("exact", "show interfaces"),
            new CatalogEntry("exact", "show interfaces brief"),
            new CatalogEntry("exact", "show interfaces description"),
            new CatalogEntry("exact", "show interfaces summary"),
            new CatalogEntry("exact", "show ipv4 interface"),
            new CatalogEntry("exact", "show ipv4 interface brief"),
            new CatalogEntry("exact", "show ipv6 interface"),
            new CatalogEntry("exact", "show ipv6 interface brief"),
            // Routing
            new CatalogEntry("exact", "show route"),
            new CatalogEntry("exact", "show route summary"),
            new CatalogEntry("exact", "show route ipv4"),
            new CatalogEntry("exact", "show route ipv6"),
            new CatalogEntry("exact", "show cef"),
            new CatalogEntry("exact", "show arp"),
            new CatalogEntry("exact", "show vrf"),
            new CatalogEntry("exact", "show vrf all"),
            // OSPF
            new CatalogEntry("exact", "show ospf neighbor"),
            new CatalogEntry("exact", "show ospf interface"),
            new CatalogEntry("exact", "show ospf database"),
            new CatalogEntry("exact", "show ospf summary"),
            // IS-IS
            new CatalogEntry("exact", "show isis adjacency"),
            new CatalogEntry("exact", "show isis interface"),
            new CatalogEntry("exact", "show isis database"),
            new CatalogEntry("exact", "show isis topology"),
            // BGP
            new CatalogEntry("exact", "show bgp summary"),
            new CatalogEntry("exact", "show bgp ipv4 unicast summary"),
            new CatalogEntry("exact", "show bgp ipv6 unicast summary"),
            new CatalogEntry("exact", "show bgp neighbors"),
            new CatalogEntry("exact", "show bgp ipv4 unicast neighbors"),
            new CatalogEntry("exact", "show bgp all unicast summary"),
            // MPLS / RSVP / LDP
            new CatalogEntry("exact", "show mpls interfaces"),
            new CatalogEntry("exact", "show mpls forwarding"),
            new CatalogEntry("exact", "show mpls ldp neighbor"),
            new CatalogEntry("exact", "show mpls ldp bindings"),
            new CatalogEntry("exact", "show rsvp neighbors"),
            new CatalogEntry("exact", "show rsvp session"),
            // L2 / discovery
            new CatalogEntry("exact", "show lldp neighbors"),
            new CatalogEntry("exact", "show lldp neighbors detail"),
            new CatalogEntry("exact", "show cdp neighbors"),
            // Mode / config
            new CatalogEntry("exact", "terminal length 0"),
            new CatalogEntry("exact", "configure"),
            new CatalogEntry("exact", "configure terminal"),
            new CatalogEntry("exact", "commit"),
            new CatalogEntry("exact", "commit confirmed"),
            new CatalogEntry("exact", "commit replace"),
            new CatalogEntry("exact", "abort"),
            new CatalogEntry("exact", "end"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "admin"),
            new CatalogEntry("exact", "admin show platform"),
            new CatalogEntry("exact", "admin show running-config"),
            // Connectivity
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "traceroute"),
            new CatalogEntry("exact", "telnet"),
            new CatalogEntry("exact", "ssh"),
            new CatalogEntry("pattern", ShowAnythingCisco),
            new CatalogEntry("pattern", @"^show\s+ipv4\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+ipv6\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+route(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+bgp(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+isis(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+ospf(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+mpls(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+hw-module(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^admin\s+show\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^terminal\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^clear\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^ping(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute(\s+\S+)+$"),
        }),
        // Cisco NX-OS (Nexus 3k/5k/6k/7k/9k). Has VDC, vPC, FEX
        // commands the IOS family doesn't share.
        new("cisco_nxos", "cisco", new[]
        {
            new CatalogEntry("exact", "show version"),
            new CatalogEntry("exact", "show running-config"),
            new CatalogEntry("exact", "show startup-config"),
            new CatalogEntry("exact", "show inventory"),
            new CatalogEntry("exact", "show hardware"),
            new CatalogEntry("exact", "show platform"),
            new CatalogEntry("exact", "show feature"),
            new CatalogEntry("exact", "show feature-set"),
            new CatalogEntry("exact", "show install all status"),
            new CatalogEntry("exact", "show environment"),
            new CatalogEntry("exact", "show environment power"),
            new CatalogEntry("exact", "show environment temperature"),
            new CatalogEntry("exact", "show environment fan"),
            new CatalogEntry("exact", "show temperature"),
            new CatalogEntry("exact", "show system resources"),
            new CatalogEntry("exact", "show system uptime"),
            new CatalogEntry("exact", "show clock"),
            new CatalogEntry("exact", "show users"),
            new CatalogEntry("exact", "show logging"),
            new CatalogEntry("exact", "show logging last 100"),
            new CatalogEntry("exact", "show processes cpu"),
            new CatalogEntry("exact", "show processes memory"),
            new CatalogEntry("exact", "show http-server"),
            new CatalogEntry("exact", "show tech-support"),
            // Interfaces / VLAN / L2
            new CatalogEntry("exact", "show interface"),
            new CatalogEntry("exact", "show interface brief"),
            new CatalogEntry("exact", "show interface description"),
            new CatalogEntry("exact", "show interface status"),
            new CatalogEntry("exact", "show interface counters"),
            new CatalogEntry("exact", "show interface counters errors"),
            new CatalogEntry("exact", "show interface transceiver"),
            new CatalogEntry("exact", "show ip interface brief"),
            new CatalogEntry("exact", "show ipv6 interface brief"),
            new CatalogEntry("exact", "show vlan"),
            new CatalogEntry("exact", "show vlan brief"),
            new CatalogEntry("exact", "show mac address-table"),
            new CatalogEntry("exact", "show spanning-tree"),
            new CatalogEntry("exact", "show spanning-tree summary"),
            new CatalogEntry("exact", "show port-channel summary"),
            new CatalogEntry("exact", "show port-channel database"),
            // VDC / vPC / FEX
            new CatalogEntry("exact", "show vdc"),
            new CatalogEntry("exact", "show vdc membership"),
            new CatalogEntry("exact", "show vdc current"),
            new CatalogEntry("exact", "show vpc"),
            new CatalogEntry("exact", "show vpc brief"),
            new CatalogEntry("exact", "show vpc role"),
            new CatalogEntry("exact", "show vpc consistency-parameters global"),
            new CatalogEntry("exact", "show fex"),
            new CatalogEntry("exact", "show fex detail"),
            // Routing
            new CatalogEntry("exact", "show ip route"),
            new CatalogEntry("exact", "show ip route summary"),
            new CatalogEntry("exact", "show ipv6 route"),
            new CatalogEntry("exact", "show ip arp"),
            new CatalogEntry("exact", "show ipv6 neighbor"),
            new CatalogEntry("exact", "show vrf"),
            new CatalogEntry("exact", "show vrf all"),
            new CatalogEntry("exact", "show ip ospf neighbor"),
            new CatalogEntry("exact", "show ip ospf interface"),
            new CatalogEntry("exact", "show ip bgp summary"),
            new CatalogEntry("exact", "show bgp ipv4 unicast summary"),
            new CatalogEntry("exact", "show ip bgp neighbors"),
            new CatalogEntry("exact", "show forwarding ipv4 route"),
            // Discovery / redundancy
            new CatalogEntry("exact", "show cdp neighbors"),
            new CatalogEntry("exact", "show cdp neighbors detail"),
            new CatalogEntry("exact", "show lldp neighbors"),
            new CatalogEntry("exact", "show lldp neighbors detail"),
            new CatalogEntry("exact", "show hsrp"),
            new CatalogEntry("exact", "show hsrp brief"),
            new CatalogEntry("exact", "show vrrp"),
            // Mode / connectivity
            new CatalogEntry("exact", "terminal length 0"),
            new CatalogEntry("exact", "configure terminal"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "end"),
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "traceroute"),
            new CatalogEntry("exact", "copy running-config startup-config"),
            new CatalogEntry("pattern", ShowAnythingCisco),
            new CatalogEntry("pattern", @"^show\s+ip\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+ipv6\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+vpc(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+vdc(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+fex(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+running-config(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^terminal\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^copy\s+\S+\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^ping(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute(\s+\S+)+$"),
        }),
        // Juniper Junos. Distinct CLI: pipe-modifiers, configure / commit
        // model, `request` for system actions.
        new("juniper_junos", "juniper", new[]
        {
            // Identity / chassis / system
            new CatalogEntry("exact", "show version"),
            new CatalogEntry("exact", "show version brief"),
            new CatalogEntry("exact", "show version detail"),
            new CatalogEntry("exact", "show chassis hardware"),
            new CatalogEntry("exact", "show chassis hardware detail"),
            new CatalogEntry("exact", "show chassis hardware extensive"),
            new CatalogEntry("exact", "show chassis routing-engine"),
            new CatalogEntry("exact", "show chassis fpc"),
            new CatalogEntry("exact", "show chassis fpc pic-status"),
            new CatalogEntry("exact", "show chassis environment"),
            new CatalogEntry("exact", "show chassis power"),
            new CatalogEntry("exact", "show chassis alarms"),
            new CatalogEntry("exact", "show system uptime"),
            new CatalogEntry("exact", "show system users"),
            new CatalogEntry("exact", "show system processes"),
            new CatalogEntry("exact", "show system processes extensive"),
            new CatalogEntry("exact", "show system storage"),
            new CatalogEntry("exact", "show system memory"),
            new CatalogEntry("exact", "show system buffers"),
            new CatalogEntry("exact", "show system alarms"),
            new CatalogEntry("exact", "show system services"),
            new CatalogEntry("exact", "show system commit"),
            new CatalogEntry("exact", "show system core-dumps"),
            new CatalogEntry("exact", "show system rollback"),
            // Interfaces
            new CatalogEntry("exact", "show interfaces"),
            new CatalogEntry("exact", "show interfaces terse"),
            new CatalogEntry("exact", "show interfaces extensive"),
            new CatalogEntry("exact", "show interfaces descriptions"),
            new CatalogEntry("exact", "show interfaces diagnostics optics"),
            new CatalogEntry("exact", "show interfaces filters"),
            new CatalogEntry("exact", "show interfaces queue"),
            // Routing
            new CatalogEntry("exact", "show route"),
            new CatalogEntry("exact", "show route summary"),
            new CatalogEntry("exact", "show route protocol bgp"),
            new CatalogEntry("exact", "show route protocol ospf"),
            new CatalogEntry("exact", "show route protocol isis"),
            new CatalogEntry("exact", "show route protocol direct"),
            new CatalogEntry("exact", "show route protocol static"),
            new CatalogEntry("exact", "show route protocol aggregate"),
            new CatalogEntry("exact", "show route table inet.0"),
            new CatalogEntry("exact", "show route table inet6.0"),
            new CatalogEntry("exact", "show route table mpls.0"),
            new CatalogEntry("exact", "show route forwarding-table"),
            new CatalogEntry("exact", "show route forwarding-table summary"),
            new CatalogEntry("exact", "show arp"),
            new CatalogEntry("exact", "show arp no-resolve"),
            new CatalogEntry("exact", "show ipv6 neighbors"),
            // BGP
            new CatalogEntry("exact", "show bgp summary"),
            new CatalogEntry("exact", "show bgp neighbor"),
            new CatalogEntry("exact", "show bgp group"),
            // OSPF / IS-IS
            new CatalogEntry("exact", "show ospf neighbor"),
            new CatalogEntry("exact", "show ospf interface"),
            new CatalogEntry("exact", "show ospf statistics"),
            new CatalogEntry("exact", "show ospf database"),
            new CatalogEntry("exact", "show ospf overview"),
            new CatalogEntry("exact", "show ospf route"),
            new CatalogEntry("exact", "show isis adjacency"),
            new CatalogEntry("exact", "show isis interface"),
            new CatalogEntry("exact", "show isis database"),
            new CatalogEntry("exact", "show isis statistics"),
            // MPLS / LDP / RSVP
            new CatalogEntry("exact", "show mpls lsp"),
            new CatalogEntry("exact", "show mpls interface"),
            new CatalogEntry("exact", "show ldp session"),
            new CatalogEntry("exact", "show ldp neighbor"),
            new CatalogEntry("exact", "show rsvp session"),
            new CatalogEntry("exact", "show rsvp neighbor"),
            new CatalogEntry("exact", "show rsvp interface"),
            // L2 / discovery
            new CatalogEntry("exact", "show lldp neighbors"),
            new CatalogEntry("exact", "show lldp local-information"),
            new CatalogEntry("exact", "show ethernet-switching table"),
            new CatalogEntry("exact", "show vlans"),
            new CatalogEntry("exact", "show spanning-tree bridge"),
            new CatalogEntry("exact", "show vrrp"),
            // Firewall / log
            new CatalogEntry("exact", "show firewall"),
            new CatalogEntry("exact", "show firewall log"),
            new CatalogEntry("exact", "show log messages"),
            // Configuration / mode
            new CatalogEntry("exact", "show configuration"),
            new CatalogEntry("exact", "show configuration interfaces"),
            new CatalogEntry("exact", "show configuration | display set"),
            new CatalogEntry("exact", "show configuration | compare"),
            new CatalogEntry("exact", "set cli screen-length 0"),
            new CatalogEntry("exact", "set cli screen-width 0"),
            new CatalogEntry("exact", "configure"),
            new CatalogEntry("exact", "configure exclusive"),
            new CatalogEntry("exact", "configure private"),
            new CatalogEntry("exact", "commit"),
            new CatalogEntry("exact", "commit confirmed"),
            new CatalogEntry("exact", "commit check"),
            new CatalogEntry("exact", "commit comment"),
            new CatalogEntry("exact", "rollback"),
            new CatalogEntry("exact", "rollback 0"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "exit configuration-mode"),
            new CatalogEntry("exact", "top"),
            new CatalogEntry("exact", "save"),
            new CatalogEntry("exact", "load merge"),
            new CatalogEntry("exact", "load replace"),
            // Connectivity
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "traceroute"),
            new CatalogEntry("exact", "telnet"),
            new CatalogEntry("exact", "ssh"),
            new CatalogEntry("exact", "monitor traffic"),
            new CatalogEntry("exact", "monitor interface"),
            new CatalogEntry("exact", "request system reboot"),
            new CatalogEntry("exact", "request system halt"),
            // Patterns
            new CatalogEntry("pattern", JunosShow),
            new CatalogEntry("pattern", @"^show\s+route(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+bgp(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+ospf(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+isis(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+interfaces(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+mpls(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+log(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+configuration(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^set\s+cli\s+screen-(length|width)\s+\d+$"),
            new CatalogEntry("pattern", @"^request\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^monitor\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^ping(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute(\s+\S+)+$"),
        }),
        // Arista EOS. CLI is mostly Cisco-IOS-compatible plus
        // Arista-specific MLAG / bash escape / EOS-specific commands.
        new("arista_eos", "arista", new[]
        {
            new CatalogEntry("exact", "show version"),
            new CatalogEntry("exact", "show running-config"),
            new CatalogEntry("exact", "show startup-config"),
            new CatalogEntry("exact", "show inventory"),
            new CatalogEntry("exact", "show platform"),
            new CatalogEntry("exact", "show environment all"),
            new CatalogEntry("exact", "show environment temperature"),
            new CatalogEntry("exact", "show environment power"),
            new CatalogEntry("exact", "show clock"),
            new CatalogEntry("exact", "show users"),
            new CatalogEntry("exact", "show logging"),
            new CatalogEntry("exact", "show processes"),
            new CatalogEntry("exact", "show processes top"),
            new CatalogEntry("exact", "show tech-support"),
            // Interfaces / L2
            new CatalogEntry("exact", "show interfaces"),
            new CatalogEntry("exact", "show interfaces description"),
            new CatalogEntry("exact", "show interfaces status"),
            new CatalogEntry("exact", "show interfaces counters"),
            new CatalogEntry("exact", "show interfaces transceiver"),
            new CatalogEntry("exact", "show interfaces transceiver detail"),
            new CatalogEntry("exact", "show ip interface brief"),
            new CatalogEntry("exact", "show ipv6 interface brief"),
            new CatalogEntry("exact", "show vlan"),
            new CatalogEntry("exact", "show vlan brief"),
            new CatalogEntry("exact", "show mac address-table"),
            new CatalogEntry("exact", "show spanning-tree"),
            new CatalogEntry("exact", "show port-channel summary"),
            new CatalogEntry("exact", "show port-channel detail"),
            // MLAG (Arista-specific)
            new CatalogEntry("exact", "show mlag"),
            new CatalogEntry("exact", "show mlag detail"),
            new CatalogEntry("exact", "show mlag interfaces"),
            new CatalogEntry("exact", "show mlag config-sanity"),
            // Discovery
            new CatalogEntry("exact", "show lldp neighbors"),
            new CatalogEntry("exact", "show lldp neighbors detail"),
            // Routing
            new CatalogEntry("exact", "show ip route"),
            new CatalogEntry("exact", "show ip route summary"),
            new CatalogEntry("exact", "show ipv6 route"),
            new CatalogEntry("exact", "show ip arp"),
            new CatalogEntry("exact", "show vrf"),
            new CatalogEntry("exact", "show vrf detail"),
            new CatalogEntry("exact", "show ip ospf neighbor"),
            new CatalogEntry("exact", "show ip ospf"),
            new CatalogEntry("exact", "show ip bgp summary"),
            new CatalogEntry("exact", "show ip bgp neighbors"),
            new CatalogEntry("exact", "show ip bgp"),
            // Multicast
            new CatalogEntry("exact", "show ip pim interface"),
            new CatalogEntry("exact", "show ip pim neighbor"),
            new CatalogEntry("exact", "show ip pim rp"),
            new CatalogEntry("exact", "show ip pim rp detail"),
            new CatalogEntry("exact", "show ip mroute"),
            // ACLs / NAT
            new CatalogEntry("exact", "show ip access-lists"),
            new CatalogEntry("exact", "show ip nat translations"),
            new CatalogEntry("exact", "show ip nat statistics"),
            // Mode / connectivity
            new CatalogEntry("exact", "terminal length 0"),
            new CatalogEntry("exact", "enable"),
            new CatalogEntry("exact", "configure"),
            new CatalogEntry("exact", "configure terminal"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "end"),
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "traceroute"),
            new CatalogEntry("exact", "bash"),
            new CatalogEntry("exact", "write"),
            new CatalogEntry("exact", "write memory"),
            new CatalogEntry("exact", "copy running-config startup-config"),
            new CatalogEntry("pattern", ShowAnythingArista),
            new CatalogEntry("pattern", @"^show\s+ip\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+ipv6\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+running-config(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+mlag(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+vrf(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^terminal\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^bash(\s+.+)?$"),
            new CatalogEntry("pattern", @"^ping(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute(\s+\S+)+$"),
        }),
        // Nokia SR OS (TiMOS classic CLI) — populated from the 7750 SR
        // Clear/Monitor/Show/Tools reference + the SR OS Interfaces show
        // command guide. Patterns cover the broad verb families
        // (show/admin/monitor/clear/file/oam/tools/configure) so
        // sub-commands not enumerated here still match.
        new("nokia_sros", "nokia", new[]
        {
            // Chassis / hardware
            new CatalogEntry("exact", "show version"),
            new CatalogEntry("exact", "show chassis"),
            new CatalogEntry("exact", "show chassis detail"),
            new CatalogEntry("exact", "show chassis environment"),
            new CatalogEntry("exact", "show chassis power-supply"),
            new CatalogEntry("exact", "show chassis ccm"),
            new CatalogEntry("exact", "show card"),
            new CatalogEntry("exact", "show card state"),
            new CatalogEntry("exact", "show card detail"),
            new CatalogEntry("exact", "show mda"),
            new CatalogEntry("exact", "show mda detail"),
            new CatalogEntry("exact", "show mcm"),
            // Ports / interfaces
            new CatalogEntry("exact", "show port"),
            new CatalogEntry("exact", "show port description"),
            new CatalogEntry("exact", "show port detail"),
            new CatalogEntry("exact", "show port statistics"),
            new CatalogEntry("exact", "show eth-tunnel"),
            new CatalogEntry("exact", "show eth-tunnel aps"),
            new CatalogEntry("exact", "show elmi"),
            new CatalogEntry("exact", "show elmi evc"),
            new CatalogEntry("exact", "show elmi uni"),
            new CatalogEntry("exact", "show interface-group-handler"),
            // Routing — base router
            new CatalogEntry("exact", "show router"),
            new CatalogEntry("exact", "show router interface"),
            new CatalogEntry("exact", "show router interface detail"),
            new CatalogEntry("exact", "show router route-table"),
            new CatalogEntry("exact", "show router route-table summary"),
            new CatalogEntry("exact", "show router arp"),
            new CatalogEntry("exact", "show router neighbor"),
            new CatalogEntry("exact", "show router static-route"),
            new CatalogEntry("exact", "show router fib 1"),
            // BGP
            new CatalogEntry("exact", "show router bgp summary"),
            new CatalogEntry("exact", "show router bgp neighbor"),
            new CatalogEntry("exact", "show router bgp routes"),
            new CatalogEntry("exact", "show router bgp paths"),
            // OSPF / IS-IS / LDP / RSVP / MPLS
            new CatalogEntry("exact", "show router ospf neighbor"),
            new CatalogEntry("exact", "show router ospf interface"),
            new CatalogEntry("exact", "show router ospf status"),
            new CatalogEntry("exact", "show router ospf database"),
            new CatalogEntry("exact", "show router isis adjacency"),
            new CatalogEntry("exact", "show router isis interface"),
            new CatalogEntry("exact", "show router isis status"),
            new CatalogEntry("exact", "show router isis database"),
            new CatalogEntry("exact", "show router ldp session"),
            new CatalogEntry("exact", "show router ldp bindings"),
            new CatalogEntry("exact", "show router ldp status"),
            new CatalogEntry("exact", "show router rsvp session"),
            new CatalogEntry("exact", "show router rsvp interface"),
            new CatalogEntry("exact", "show router rsvp neighbor"),
            new CatalogEntry("exact", "show router rsvp status"),
            new CatalogEntry("exact", "show router mpls lsp"),
            new CatalogEntry("exact", "show router mpls lsp terminate"),
            new CatalogEntry("exact", "show router mpls lsp transit"),
            new CatalogEntry("exact", "show router mpls interface"),
            new CatalogEntry("exact", "show router mpls status"),
            new CatalogEntry("exact", "show router mpls sr-te-lsp"),
            // Services
            new CatalogEntry("exact", "show service service-using"),
            new CatalogEntry("exact", "show service sap-using"),
            new CatalogEntry("exact", "show service sdp"),
            new CatalogEntry("exact", "show service sdp-using"),
            new CatalogEntry("exact", "show service customer"),
            // System / log / users
            new CatalogEntry("exact", "show system information"),
            new CatalogEntry("exact", "show system cpu"),
            new CatalogEntry("exact", "show system memory-pools"),
            new CatalogEntry("exact", "show system thresholds"),
            new CatalogEntry("exact", "show users"),
            new CatalogEntry("exact", "show time"),
            new CatalogEntry("exact", "show uptime"),
            new CatalogEntry("exact", "show log"),
            new CatalogEntry("exact", "show log event-control"),
            new CatalogEntry("exact", "show log applications"),
            new CatalogEntry("exact", "show boot-messages"),
            new CatalogEntry("exact", "show debug"),
            // Config / save / rollback
            new CatalogEntry("exact", "admin display-config"),
            new CatalogEntry("exact", "admin save"),
            new CatalogEntry("exact", "admin save rollback"),
            new CatalogEntry("exact", "admin reboot"),
            new CatalogEntry("exact", "admin reboot now"),
            new CatalogEntry("exact", "admin disconnect"),
            new CatalogEntry("exact", "admin tech-support"),
            // Environment / shell
            new CatalogEntry("exact", "environment more"),
            new CatalogEntry("exact", "environment no more"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "exit all"),
            new CatalogEntry("exact", "logout"),
            new CatalogEntry("exact", "tree"),
            new CatalogEntry("exact", "history"),
            new CatalogEntry("exact", "pwc"),
            new CatalogEntry("exact", "help"),
            new CatalogEntry("exact", "info"),
            new CatalogEntry("exact", "info detail"),
            // OAM / connectivity
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "traceroute"),
            new CatalogEntry("exact", "telnet"),
            new CatalogEntry("exact", "ssh"),
            new CatalogEntry("exact", "mrinfo"),
            new CatalogEntry("exact", "mstat"),
            new CatalogEntry("exact", "mtrace"),
            // Patterns — broad coverage of the verb families. Exact
            // entries above stay for "did you mean" suggestions.
            new CatalogEntry("pattern", SrosShow),
            new CatalogEntry("pattern", @"^show\s+router(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+service(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^show\s+port\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^show\s+log\s+log-id\s+\d+$"),
            new CatalogEntry("pattern", @"^admin\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^monitor\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^clear\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^debug\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^file\s+(dir|copy|move|delete|md5|sha256|attrib|cd|type|version)(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^oam\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^tools\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^configure(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^ping(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute(\s+\S+)+$"),
        }),
        // Nokia SR Linux — populated from the 24-7 system-mgmt
        // operational commands reference + the learn.srlinux.dev
        // troubleshooting catalogue. The pattern set covers the four
        // top-level command families (show, info, info from state,
        // info from running, tools, monitor, file, enter, diff,
        // environment) so commands not enumerated here still match.
        new("nokia_srl", "nokia", new[]
        {
            // Identity / platform / chassis
            new CatalogEntry("exact", "show version"),
            new CatalogEntry("exact", "show platform"),
            new CatalogEntry("exact", "show platform chassis"),
            new CatalogEntry("exact", "show platform environment"),
            new CatalogEntry("exact", "show platform redundancy"),
            new CatalogEntry("exact", "show platform fan-tray"),
            new CatalogEntry("exact", "show platform power-supply"),
            // Interfaces
            new CatalogEntry("exact", "show interface"),
            new CatalogEntry("exact", "show interface brief"),
            new CatalogEntry("exact", "show interface all"),
            new CatalogEntry("exact", "show interface mgmt0"),
            // LAG
            new CatalogEntry("exact", "show lag"),
            // ACL
            new CatalogEntry("exact", "show acl summary"),
            new CatalogEntry("exact", "show acl cpm-filter ipv4-filter"),
            // ARP / ND
            new CatalogEntry("exact", "show arpnd arp-entries"),
            new CatalogEntry("exact", "show arpnd neighbors"),
            // Network-instance routing / protocols
            new CatalogEntry("exact", "show network-instance summary"),
            new CatalogEntry("exact", "show network-instance default interfaces"),
            new CatalogEntry("exact", "show network-instance default route-table summary"),
            new CatalogEntry("exact", "show network-instance default protocols bgp summary"),
            new CatalogEntry("exact", "show network-instance default protocols bgp neighbor"),
            new CatalogEntry("exact", "show network-instance default protocols bgp routes ipv4 summary"),
            new CatalogEntry("exact", "show network-instance default protocols ospf status"),
            new CatalogEntry("exact", "show network-instance default protocols ospf neighbor"),
            new CatalogEntry("exact", "show network-instance default protocols ospf database"),
            new CatalogEntry("exact", "show network-instance default protocols ospf statistics"),
            new CatalogEntry("exact", "show network-instance default protocols isis summary"),
            new CatalogEntry("exact", "show network-instance default protocols isis adjacency"),
            new CatalogEntry("exact", "show network-instance default protocols isis database"),
            new CatalogEntry("exact", "show network-instance default tunnel-table all"),
            // LLDP — SR Linux puts LLDP under `system`, NOT at the top
            // level. `show lldp …` is rejected by the parser (the user
            // who tried it saw: "Unknown token 'lldp'. Options are
            // ['acl', 'arpnd', 'interface', 'lag', 'network-instance',
            // 'platform', 'system', 'tunnel', …]"). Always use
            // `show system lldp …` or `info from state system lldp …`.
            new CatalogEntry("exact", "show system lldp neighbor"),
            new CatalogEntry("exact", "show system lldp neighbor detail"),
            new CatalogEntry("exact", "show system lldp interface"),
            new CatalogEntry("exact", "show system lldp statistics"),
            new CatalogEntry("exact", "info from state system lldp"),
            new CatalogEntry("exact", "info from state system lldp neighbor"),
            new CatalogEntry("exact", "info from state system lldp interface"),
            new CatalogEntry("exact", "info system lldp"),
            // Info / state browsing — broad starting points
            new CatalogEntry("exact", "info"),
            new CatalogEntry("exact", "info detail"),
            new CatalogEntry("exact", "info flat"),
            new CatalogEntry("exact", "info from state"),
            new CatalogEntry("exact", "info from state system information"),
            new CatalogEntry("exact", "info from state interface"),
            new CatalogEntry("exact", "info from state network-instance"),
            new CatalogEntry("exact", "info from state platform"),
            new CatalogEntry("exact", "info from state tunnel vxlan-tunnel"),
            new CatalogEntry("exact", "info system mirroring"),
            // Mode / context
            new CatalogEntry("exact", "enter candidate"),
            new CatalogEntry("exact", "enter candidate exclusive"),
            new CatalogEntry("exact", "enter candidate private"),
            new CatalogEntry("exact", "enter running"),
            new CatalogEntry("exact", "enter show"),
            new CatalogEntry("exact", "enter state"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "exit all"),
            new CatalogEntry("exact", "quit"),
            // Commit / discard / save
            new CatalogEntry("exact", "commit now"),
            new CatalogEntry("exact", "commit stay"),
            new CatalogEntry("exact", "commit save"),
            new CatalogEntry("exact", "commit validate"),
            new CatalogEntry("exact", "commit confirmed"),
            new CatalogEntry("exact", "discard now"),
            new CatalogEntry("exact", "discard stay"),
            new CatalogEntry("exact", "save"),
            new CatalogEntry("exact", "save detail"),
            new CatalogEntry("exact", "save text"),
            // Diff / compare
            new CatalogEntry("exact", "diff"),
            new CatalogEntry("exact", "diff baseline"),
            new CatalogEntry("exact", "diff candidate"),
            new CatalogEntry("exact", "diff running"),
            new CatalogEntry("exact", "diff startup"),
            // Environment / CLI
            new CatalogEntry("exact", "environment show"),
            new CatalogEntry("exact", "environment save"),
            new CatalogEntry("exact", "environment save home"),
            new CatalogEntry("exact", "tree"),
            new CatalogEntry("exact", "tree flat"),
            new CatalogEntry("exact", "history"),
            new CatalogEntry("exact", "history clear"),
            new CatalogEntry("exact", "pwc"),
            new CatalogEntry("exact", "help"),
            new CatalogEntry("exact", "cls"),
            // OAM / connectivity
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "ping6"),
            new CatalogEntry("exact", "traceroute"),
            new CatalogEntry("exact", "traceroute6"),
            new CatalogEntry("exact", "tcptraceroute"),
            // Tools / shell / file
            new CatalogEntry("exact", "tools"),
            new CatalogEntry("exact", "monitor"),
            new CatalogEntry("exact", "tech-support"),
            new CatalogEntry("exact", "bash"),
            new CatalogEntry("exact", "file ls"),
            new CatalogEntry("exact", "file pwd"),
            // Patterns — broad family coverage
            new CatalogEntry("pattern", @"^show\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^info(\s+(detail|flat|use-proto-json|depth\s+\d+))*(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^info\s+from\s+(state|running)(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^info\s+system(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^info\s+acl(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^tools\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^monitor(\s+(recursive|sample))?(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^enter\s+(candidate|running|show|state)(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^diff\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^environment\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^file\s+(ls|cd|cp|mkdir|mv|rm|pwd|cat|md5sum|touch)(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^bash(\s+.+)?$"),
            new CatalogEntry("pattern", @"^ping6?(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute6?(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^tcptraceroute(\s+\S+)+$"),
        }),
        // Huawei VRP (S-series, NE-series, AR-series). `display` is the
        // read verb; `system-view`/`quit` mirror Cisco's configure/exit.
        new("huawei", "huawei", new[]
        {
            // System / hardware
            new CatalogEntry("exact", "display version"),
            new CatalogEntry("exact", "display device"),
            new CatalogEntry("exact", "display device manufacture-info"),
            new CatalogEntry("exact", "display elabel"),
            new CatalogEntry("exact", "display power"),
            new CatalogEntry("exact", "display environment"),
            new CatalogEntry("exact", "display fan"),
            new CatalogEntry("exact", "display temperature all"),
            new CatalogEntry("exact", "display cpu-usage"),
            new CatalogEntry("exact", "display memory-usage"),
            new CatalogEntry("exact", "display clock"),
            new CatalogEntry("exact", "display users"),
            new CatalogEntry("exact", "display history-command"),
            new CatalogEntry("exact", "display diagnostic-information"),
            new CatalogEntry("exact", "display logbuffer"),
            new CatalogEntry("exact", "display trapbuffer"),
            new CatalogEntry("exact", "display alarm all"),
            new CatalogEntry("exact", "display saved-configuration"),
            new CatalogEntry("exact", "display current-configuration"),
            new CatalogEntry("exact", "display current-configuration interface"),
            new CatalogEntry("exact", "display startup"),
            // Interfaces / L2
            new CatalogEntry("exact", "display interface"),
            new CatalogEntry("exact", "display interface brief"),
            new CatalogEntry("exact", "display interface description"),
            new CatalogEntry("exact", "display ip interface"),
            new CatalogEntry("exact", "display ip interface brief"),
            new CatalogEntry("exact", "display ipv6 interface"),
            new CatalogEntry("exact", "display ipv6 interface brief"),
            new CatalogEntry("exact", "display arp"),
            new CatalogEntry("exact", "display arp brief"),
            new CatalogEntry("exact", "display ipv6 neighbors"),
            new CatalogEntry("exact", "display vlan"),
            new CatalogEntry("exact", "display vlan brief"),
            new CatalogEntry("exact", "display mac-address"),
            new CatalogEntry("exact", "display stp"),
            new CatalogEntry("exact", "display stp brief"),
            new CatalogEntry("exact", "display lldp neighbor"),
            new CatalogEntry("exact", "display lldp neighbor brief"),
            new CatalogEntry("exact", "display lldp local"),
            // Routing
            new CatalogEntry("exact", "display ip routing-table"),
            new CatalogEntry("exact", "display ip routing-table statistics"),
            new CatalogEntry("exact", "display ipv6 routing-table"),
            new CatalogEntry("exact", "display ip routing-table protocol bgp"),
            new CatalogEntry("exact", "display ip routing-table protocol ospf"),
            new CatalogEntry("exact", "display ip routing-table protocol isis"),
            new CatalogEntry("exact", "display ip routing-table protocol static"),
            new CatalogEntry("exact", "display ip vpn-instance"),
            new CatalogEntry("exact", "display vrf"),
            // BGP / OSPF / IS-IS / MPLS
            new CatalogEntry("exact", "display bgp peer"),
            new CatalogEntry("exact", "display bgp peer verbose"),
            new CatalogEntry("exact", "display bgp routing-table"),
            new CatalogEntry("exact", "display bgp ipv4 unicast peer"),
            new CatalogEntry("exact", "display ospf peer"),
            new CatalogEntry("exact", "display ospf peer brief"),
            new CatalogEntry("exact", "display ospf interface"),
            new CatalogEntry("exact", "display ospf lsdb"),
            new CatalogEntry("exact", "display isis peer"),
            new CatalogEntry("exact", "display isis interface"),
            new CatalogEntry("exact", "display isis lsdb"),
            new CatalogEntry("exact", "display mpls lsp"),
            new CatalogEntry("exact", "display mpls interface"),
            new CatalogEntry("exact", "display mpls ldp peer"),
            // SSH / NTP / SNMP
            new CatalogEntry("exact", "display ssh server status"),
            new CatalogEntry("exact", "display ssh user-information"),
            new CatalogEntry("exact", "display ntp-service status"),
            new CatalogEntry("exact", "display ntp-service sessions"),
            new CatalogEntry("exact", "display snmp-agent statistics"),
            // Mode / paging / connectivity
            new CatalogEntry("exact", "screen-length 0 temporary"),
            new CatalogEntry("exact", "screen-length disable"),
            new CatalogEntry("exact", "system-view"),
            new CatalogEntry("exact", "quit"),
            new CatalogEntry("exact", "return"),
            new CatalogEntry("exact", "save"),
            new CatalogEntry("exact", "ping"),
            new CatalogEntry("exact", "tracert"),
            new CatalogEntry("exact", "telnet"),
            new CatalogEntry("exact", "ssh"),
            new CatalogEntry("pattern", ShowAnythingHuawei),
            new CatalogEntry("pattern", @"^display\s+current-configuration(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^display\s+interface(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^display\s+ip\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^display\s+bgp(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^display\s+ospf(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^display\s+isis(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^display\s+mpls(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^display\s+lldp(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^screen-length\s+\d+\s+temporary$"),
            new CatalogEntry("pattern", @"^ping(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^tracert(\s+\S+)+$"),
        }),
        // Fortinet FortiOS (FortiGate). CLI splits into get/show
        // (read), config (write), execute (actions), diagnose
        // (debug/troubleshoot). Patterns cover the four families.
        new("fortinet", "fortinet", new[]
        {
            // System / status (`get`)
            new CatalogEntry("exact", "get system status"),
            new CatalogEntry("exact", "get system performance status"),
            new CatalogEntry("exact", "get system info admin status"),
            new CatalogEntry("exact", "get system ha status"),
            new CatalogEntry("exact", "get system fortiguard-service status"),
            new CatalogEntry("exact", "get system checksum status"),
            new CatalogEntry("exact", "get hardware status"),
            new CatalogEntry("exact", "get system interface"),
            new CatalogEntry("exact", "get system interface transceiver"),
            new CatalogEntry("exact", "get system arp"),
            // Routing
            new CatalogEntry("exact", "get router info"),
            new CatalogEntry("exact", "get router info protocol"),
            new CatalogEntry("exact", "get router info routing-table all"),
            new CatalogEntry("exact", "get router info routing-table bgp"),
            new CatalogEntry("exact", "get router info routing-table database"),
            new CatalogEntry("exact", "get router info bgp summary"),
            new CatalogEntry("exact", "get router info bgp neighbors"),
            new CatalogEntry("exact", "get router info ospf neighbor"),
            new CatalogEntry("exact", "get router info ospf interface"),
            // Show / config dump
            new CatalogEntry("exact", "show"),
            new CatalogEntry("exact", "show full-configuration"),
            new CatalogEntry("exact", "show system interface"),
            new CatalogEntry("exact", "show firewall acl"),
            new CatalogEntry("exact", "show firewall policy"),
            new CatalogEntry("exact", "show firewall address"),
            new CatalogEntry("exact", "show vpn ipsec phase1-interface"),
            new CatalogEntry("exact", "show vpn ipsec phase2-interface"),
            // Diagnose (read-only debug)
            new CatalogEntry("exact", "diagnose hardware deviceinfo nic"),
            new CatalogEntry("exact", "diagnose hardware sysinfo memory"),
            new CatalogEntry("exact", "diagnose hardware sysinfo interrupts"),
            new CatalogEntry("exact", "diagnose hardware sysinfo slab"),
            new CatalogEntry("exact", "diagnose hardware deviceinfo disk"),
            new CatalogEntry("exact", "diagnose ip address list"),
            new CatalogEntry("exact", "diagnose ip arp list"),
            new CatalogEntry("exact", "diagnose ip rtcache list"),
            new CatalogEntry("exact", "diagnose ip router bgp all enable"),
            new CatalogEntry("exact", "diagnose firewall iplist list"),
            new CatalogEntry("exact", "diagnose firewall proute list"),
            new CatalogEntry("exact", "diagnose netlink interface list"),
            new CatalogEntry("exact", "diagnose sys session list"),
            new CatalogEntry("exact", "diagnose sys session full-stat"),
            new CatalogEntry("exact", "diagnose sys session filter clear"),
            new CatalogEntry("exact", "diagnose sys top"),
            new CatalogEntry("exact", "diagnose sys top-mem"),
            new CatalogEntry("exact", "diagnose sys top-all"),
            new CatalogEntry("exact", "diagnose sys mpstat"),
            new CatalogEntry("exact", "diagnose sys vd list"),
            new CatalogEntry("exact", "diagnose sys cmdb info"),
            new CatalogEntry("exact", "diagnose autoupdate versions"),
            new CatalogEntry("exact", "diagnose autoupdate status"),
            new CatalogEntry("exact", "diagnose vpn tunnel list"),
            new CatalogEntry("exact", "diagnose vpn ike gateway list"),
            new CatalogEntry("exact", "diagnose user banned-ip list"),
            new CatalogEntry("exact", "diagnose debug crashlog read"),
            new CatalogEntry("exact", "diagnose debug crashlog get"),
            new CatalogEntry("exact", "diagnose debug enable"),
            new CatalogEntry("exact", "diagnose debug disable"),
            new CatalogEntry("exact", "diagnose log test"),
            new CatalogEntry("exact", "diagnose sys ha status"),
            new CatalogEntry("exact", "diagnose sys ha checksum cluster"),
            new CatalogEntry("exact", "diagnose sys ha hadiff status"),
            new CatalogEntry("exact", "diagnose switch-controller switch-info mac-table"),
            new CatalogEntry("exact", "diagnose switch-controller switch-info port-stats"),
            new CatalogEntry("exact", "diagnose switch-controller switch-info trunk"),
            // Execute (action) — read-style only; reboots/shutdowns
            // belong in policy, not this allowlist.
            new CatalogEntry("exact", "execute log display"),
            new CatalogEntry("exact", "execute log filter reset"),
            new CatalogEntry("exact", "execute traceroute"),
            new CatalogEntry("exact", "execute ping"),
            new CatalogEntry("exact", "execute disconnect-admin-session"),
            new CatalogEntry("exact", "execute tac report"),
            new CatalogEntry("exact", "exec log fortiguard test-connectivity"),
            // Mode
            new CatalogEntry("exact", "config global"),
            new CatalogEntry("exact", "end"),
            new CatalogEntry("exact", "exit"),
            new CatalogEntry("exact", "next"),
            // Patterns — broad family coverage
            new CatalogEntry("pattern", FortinetGet),
            new CatalogEntry("pattern", @"^show(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^diag(nose)?(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^exec(ute)?(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^config\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^edit\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^set\s+\S+(\s+.+)?$"),
            new CatalogEntry("pattern", @"^unset\s+\S+(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^fnsysctl(\s+.+)?$"),
        }),
        // Plain Linux shell (Debian/Ubuntu/RHEL/Alpine on a network
        // device or jump host). Catalog stays narrow on purpose — broad
        // pattern coverage handles the common read-only verbs.
        new("linux", "linux", new[]
        {
            new CatalogEntry("exact", "uname -a"),
            new CatalogEntry("exact", "uname -r"),
            new CatalogEntry("exact", "hostname"),
            new CatalogEntry("exact", "hostname -f"),
            new CatalogEntry("exact", "hostname -i"),
            new CatalogEntry("exact", "uptime"),
            new CatalogEntry("exact", "whoami"),
            new CatalogEntry("exact", "id"),
            new CatalogEntry("exact", "date"),
            new CatalogEntry("exact", "df -h"),
            new CatalogEntry("exact", "df -hT"),
            new CatalogEntry("exact", "free -h"),
            new CatalogEntry("exact", "free -m"),
            new CatalogEntry("exact", "vmstat"),
            new CatalogEntry("exact", "iostat"),
            new CatalogEntry("exact", "top -bn1"),
            new CatalogEntry("exact", "ps aux"),
            new CatalogEntry("exact", "ps -ef"),
            new CatalogEntry("exact", "lsof -i"),
            new CatalogEntry("exact", "lscpu"),
            new CatalogEntry("exact", "lsblk"),
            new CatalogEntry("exact", "lspci"),
            new CatalogEntry("exact", "lsmod"),
            new CatalogEntry("exact", "dmesg"),
            new CatalogEntry("exact", "journalctl -xe"),
            new CatalogEntry("exact", "ip addr"),
            new CatalogEntry("exact", "ip a"),
            new CatalogEntry("exact", "ip link"),
            new CatalogEntry("exact", "ip route"),
            new CatalogEntry("exact", "ip -6 route"),
            new CatalogEntry("exact", "ip neigh"),
            new CatalogEntry("exact", "ss -tunlp"),
            new CatalogEntry("exact", "netstat -rn"),
            new CatalogEntry("exact", "netstat -tunlp"),
            new CatalogEntry("exact", "arp -an"),
            new CatalogEntry("exact", "mount"),
            new CatalogEntry("exact", "cat /proc/cpuinfo"),
            new CatalogEntry("exact", "cat /proc/meminfo"),
            new CatalogEntry("exact", "cat /etc/os-release"),
            new CatalogEntry("pattern", LinuxStat),
            new CatalogEntry("pattern", @"^(ls|cat|tail|head|grep|find|wc|awk|sed|cut|sort|uniq|tr|du|stat|file|which|whereis|less|more)(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^ip\s+(addr|address|a|link|l|route|r|neigh|n|-6\s+\S+)(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^ss(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^netstat(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^ping6?(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^traceroute6?(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^systemctl\s+(status|is-active|is-enabled|list-units|list-unit-files|show)(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^journalctl(\s+\S+)+$"),
            new CatalogEntry("pattern", @"^docker\s+(ps|images|inspect|logs|stats|version|info)(\s+\S+)*$"),
            new CatalogEntry("pattern", @"^kubectl\s+(get|describe|logs|version|top|cluster-info|config)(\s+\S+)*$"),
        }),
    };

    public static async Task SeedAsync(IServiceScopeFactory scopeFactory, ILogger logger)
    {
        using var scope = scopeFactory.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        await SeedDefaultsAsync(db, logger);

    }

    private static async Task SeedDefaultsAsync(AppDbContext db, ILogger logger)
    {
        // Same advisory-lock pattern DefaultSnippetsSeedService uses.
        // Two concurrent boots must not double-insert the baseline.
        const long lockKey = 0x5311_9E75_0000_0002;
        await using var tx = await db.Database.BeginTransactionAsync();
        try
        {
            await db.Database.ExecuteSqlRawAsync(
                "SELECT pg_advisory_xact_lock({0})", lockKey);

            // Pull every row (active or not) so we can detect "admin
            // deleted this seed entry" and skip re-inserting it.
            var existing = await db.VendorCommands
                .Select(v => new { v.DeviceType, v.Kind, v.Value, v.IsActive })
                .ToListAsync();

            var seenAny = existing.Select(e => (e.DeviceType, e.Kind, e.Value))
                .ToHashSet();

            var now = DateTime.UtcNow;
            var inserted = 0;
            foreach (var catalog in Catalogs)
            {
                foreach (var entry in catalog.Entries)
                {
                    var key = (catalog.DeviceType, entry.Kind, entry.Value);
                    // Already present (active OR soft-deleted) → leave alone.
                    if (seenAny.Contains(key)) continue;

                    db.VendorCommands.Add(new VendorCommandModel
                    {
                        VendorCommandId = Guid.NewGuid(),
                        DeviceType = catalog.DeviceType,
                        VendorFamily = catalog.VendorFamily,
                        Kind = entry.Kind,
                        Value = entry.Value,
                        Source = VendorCommandModel.SourceSeed,
                        IsActive = true,
                        CreatedAt = now,
                        UpdatedAt = now,
                    });
                    inserted++;
                }
            }

            if (inserted > 0)
            {
                await db.SaveChangesAsync();
                await tx.CommitAsync();
                logger.LogInformation(
                    "Seeded {Count} vendor_command(s)",
                    inserted);
            }
            else
            {
                await tx.CommitAsync();
            }
        }
        catch
        {
            await tx.RollbackAsync();
            throw;
        }
    }
}
