<script lang="ts">
  import DocLayout from '../../_components/DocLayout.svelte';
  import Callout from '../../_components/Callout.svelte';
</script>

<DocLayout
  title="Artifacts"
  lead="Every generated document, organised by origin: Reports come out of workflow runs, Exports are produced without a workflow — by the agent in chat or a direct API call. This is the audit view: who created what, when, and from which prompt or run."
>
  <Callout tone="where" title="Where to find it">
    List: <a href="/admin/artifacts"><code>/admin/artifacts</code></a> ·
    Detail: <code>/admin/artifacts/{'{id}'}</code>. Also in the sidebar under
    <em>Operate</em>, and pinnable to the dashboard as a quick-access shortcut.
  </Callout>
  <Callout tone="admin" title="Admin only">
    Requires the <code>admin</code> role (backend capability
    <code>report.manage</code>).
  </Callout>

  <section>
    <h2>Concept</h2>
    <p>
      Certain tools and workflow steps produce <strong>document
      artefacts</strong> — HTML, CSV, XLSX or PDF files derived from queries
      the agent or a workflow step ran. Each lands in the artefact store with
      a metadata row recording its origin. The view splits them by that
      origin:
    </p>
    <dl>
      <dt>Report</dt>
      <dd>
        Generated by a <strong>workflow run</strong>. Each row links to the
        run that produced it, and is attributed to the user who triggered the
        run — or to the schedule, when the run was fired by one.
      </dd>
      <dt>Export</dt>
      <dd>
        Generated <strong>without a workflow</strong>: by the agent in chat
        (rows link back to the conversation) or through a direct API call.
      </dd>
    </dl>
    <p>
      The active section is kept in the URL (<code>?section=export</code>),
      so a bookmarked or pinned link opens on the tab you left.
    </p>
    <Callout tone="warning" title="Prompt-read is itself audited">
      Opening the detail view of an agent-generated document decrypts its
      triggering prompt and leaves a <code>report.read_prompt</code> audit
      row — admins reading prompts are also audited. There is no way to view
      stored prompts without leaving a trace.
    </Callout>
  </section>

  <section>
    <h2>List page</h2>
    <p>
      Route: <code>/admin/artifacts</code>. Section tabs, a filter row
      (title search, format, user, creation-date window — the tab replaces
      the source filter), then a paginated table. Rows can be downloaded or
      deleted in place; deletion is soft, with a purge after the retention
      grace period.
    </p>
  </section>

  <section>
    <h2>Detail page</h2>
    <p>
      Route: <code>/admin/artifacts/{'{id}'}</code>. Opens from the row
      link. Shows:
    </p>
    <ul>
      <li>Full metadata (filename, format, size, SHA-256, expiry).</li>
      <li>The origin: the triggering prompt and conversation for agent
        exports, or the workflow / run / trigger for reports.</li>
      <li>An inline preview (HTML, PDF, first rows of CSV).</li>
      <li>A <em>Download</em> button that streams the file from the backend
        artefact store directly — no intermediate base64 in the browser.</li>
    </ul>
  </section>

  <section>
    <h2>Delivering a document by email</h2>
    <p>
      Ask the agent in <a href="/docs/ai/chat">chat</a> to "email me the
      report" and it generates the file, then attaches it through the
      <code>fw_email</code> integration. The attachment is passed <strong>by
      reference</strong>, not by value: the agent writes
      <code>{'${report:<report_artifact_id>}'}</code> into the attachment and
      the backend splices in the file bytes at send time. The model never
      carries the base64 blob, so attachments no longer arrive truncated or
      empty.
    </p>
    <Callout tone="success" title="Several formats in one email">
      Ask for "PDF and Excel" — or "all formats" — and you get a single email
      with one attachment per format: the agent generates each file and lists
      every <code>{'${report:…}'}</code> reference as its own attachment. Keep
      the combined size under ~10&nbsp;MB (the mail relay's cap).
    </Callout>
    <p>
      If a reference can't be resolved — the document was purged by the
      retention policy or the id is wrong — the send fails with a clear error
      instead of attaching a corrupt file, and the agent regenerates the
      document before retrying.
    </p>
  </section>

  <section>
    <h2>Adding it as a shortcut</h2>
    <p>
      On the dashboard, open <em>Quick access → Edit</em> and pick
      <em>Artifacts</em> from the add selector. The shortcut behaves like any
      other quick link — reorder or remove it from the same edit mode.
    </p>
  </section>

  <section>
    <h2>Related chapters</h2>
    <ul>
      <li><a href="/docs/admin/audit">Audit log</a> — every read/write on artifacts leaves a row here.</li>
      <li><a href="/docs/ai/chat">AI chat</a> — where exports come from.</li>
      <li><a href="/docs/runs">Runs</a> — where reports come from.</li>
    </ul>
  </section>
</DocLayout>
